version: '3.1'

services:

  ping-mongo:
    image: ping-mongo
    container_name: ping-mongo
    restart: always
    build:
      context: .
      dockerfile: ./env/database/Dockerfile
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./env/database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - ping-network

  ping-ms:
    image: kipu23/ping-ms:${APP_VERSION}
    container_name: ping-ms
    restart: always
    ports:
      - 6002:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PingDatabaseSettings__ConnectionString=mongodb://ping:pong@ping-mongo:27017/ping
      - PingDatabaseSettings__DatabaseName=ping
      - PingDatabaseSettings__CollectionName=pings
    networks:
      - ping-network

  ping-ui:
    image: kipu23/ping-ui:${APP_VERSION}
    container_name: ping-ui
    restart: always
    ports:
      - 6001:80
    networks:
      - ping-network

  ping-prometheus:
    image: prom/prometheus:0.18.0
    container_name: ping-prometheus
    restart: always
    ports:
      - "6090:9090"
    volumes:
      - ./env/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./env/prometheus:/prometheus
    command:
      - "-config.file=/etc/prometheus/prometheus.yml"
    networks:
      - ping-network

  ping-grafana:
    image: grafana/grafana:latest
    container_name: ping-grafana
    restart: always
    ports:
      - "6091:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - ping-prometheus
    volumes:
      - ./env/grafana/prometheus-datasource.yaml:/etc/grafana/provisioning/datasources/prometheus-datasource.yaml
      - ./env/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
    networks:
      - ping-network

networks:
  ping-network:
    name: ping-network