version: '3.1'

services:

  ping-ms:
    image: ping-ms
    container_name: ping-ms
    restart: always
    build:
      context: .
      dockerfile: ./src/ms/Dockerfile

  ping-ui:
    image: ping-ui
    container_name: ping-ui
    restart: always
    build:
      context: .
      dockerfile: ./src/ui/Dockerfile
