version: '3.1'

services:

  ping-pong-ms:
    image: ping-pong-ms
    container_name: ping-pong-ms
    restart: always
    build:
      context: .
      dockerfile: ./src/ms/Dockerfile

  ping-pong-ui:
    image: ping-pong-ui
    container_name: ping-pong-ui
    restart: always
    build:
      context: .
      dockerfile: ./src/ui/Dockerfile
