version: '3.1'

services:

  ping-mongo:
    image: ping-mongo
    container_name: ping-mongo
    restart: always
    build:
      context: .
      dockerfile: ./env/database/Dockerfile
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./env/database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - ping-network

  ping-ms:
    image: ping-ms
    container_name: ping-ms
    restart: always
    build:
      context: .
      dockerfile: ./src/ms/Dockerfile
    ports:
      - 6002:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PingDatabaseSettings__ConnectionString=mongodb://ping:pong@ping-mongo:27017/ping
      - PingDatabaseSettings__DatabaseName=ping
      - PingDatabaseSettings__CollectionName=pings
    networks:
      - ping-network

  ping-ui:
    image: ping-ui
    container_name: ping-ui
    restart: always
    build:
      context: .
      dockerfile: ./src/ui/Dockerfile
    ports:
      - 6001:80
    networks:
      - ping-network

networks:
  ping-network:
    name: ping-network