apiVersion: v1
kind: ConfigMap
metadata:
  name: ping-pong-ui-config
  namespace: ping-pong
  labels:
    app: ping-pong
    tier: ui
data:
  environment.json: |    
    {
      "production": true,
      "settings": {
        "backend": "http://8fc072c0923e49668fbc.westeurope.aksapp.io/api/ping"
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: ping-pong-ui
  namespace: ping-pong
  labels:
    app: ping-pong
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: ping-pong
    tier: frontend
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-ui
  namespace: ping-pong
  labels:
    app: ping-pong
    tier: frontend
spec:
  selector:
    matchLabels:
      app: ping-pong
      tier: frontend
  replicas: 2
  template:
    metadata:
      name: ping-pong-ui
      labels:
        app: ping-pong
        tier: frontend
    spec:
      containers:
        - name: ping-pong-ui
          image: kipu23/ping-pong-ui:1.0.1
          volumeMounts:
            - name: config
              mountPath: /usr/share/nginx/html/assets/environments/environment.json
              subPath: environment.json
      volumes:
        - name: config
          configMap:
            name: ping-pong-ui-config