apiVersion: v1
kind: ConfigMap
metadata:
  name: ping-pong-mongo-init
  labels:
    app: ping-pong
    tier: database  
data:
  mongo-init.js: |
    print('Starting mongo-init.js #################################################################');

    db = db.getSiblingDB('ping');

    db.createUser({
        user: 'ping',
        pwd: 'pong',
        roles: [
          {
            role: 'readWrite',
            db: 'ping'
          }
        ]
    });

    db.createCollection('pings');